version: 'latest'

services:
  userDatabase:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
    volumes:
        - userdata:/var/lib/postgresql/data
    ports:
      - "${db_port}:5432"
  redis:
    image: "redis"
    container_name: "redis-pennyearned"
    restart: always
    ports:
      - "${redis_port}:6379"
    command: redis-server --requirepass ${redis_password}
    volumes:
      - pennyearnedRedis:/data
volumes:
  userdata:
  pennyearnedRedis:
    driver: local
