package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"errors"
	"fmt"

	"github.com/vibovenkat123/pennyearned-server/graph/model"
	dbHelpers "github.com/vibovenkat123/pennyearned-server/internal/db/helpers"
)

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input model.NewExpense) (*model.Expense, error) {
	expense := dbHelpers.NewExpense(input.OwnerID, input.Name, input.Spent)
	data := &model.Expense{
		ID:      expense.ID,
		OwnerID: expense.OwnerID,
		Name:    expense.Name,
		Spent:   expense.Spent,
	}
	return data, nil
}

// UpdateExpense is the resolver for the updateExpense field.
func (r *mutationResolver) UpdateExpense(ctx context.Context, input model.UpdateExpenseInput) (*model.Expense, error) {
	original := dbHelpers.GetExpenseById(input.ID)
	id := input.ID
	ownerId := input.OwnerID
	name := input.Name
	spent := input.Spent
	if ownerId == nil {
		ownerId = &original.OwnerID
	}
	if name == nil {
		name = &original.Name
	}
	if spent == nil {
		spent = &original.Spent
	}
	expense := dbHelpers.Expense{
		ID:      id,
		Name:    *name,
		Spent:   *spent,
		OwnerID: *ownerId,
	}
	expense = dbHelpers.UpdateExpense(expense)
	data := &model.Expense{
		ID:      expense.ID,
		OwnerID: expense.OwnerID,
		Name:    expense.Name,
		Spent:   expense.Spent,
	}
	if data.ID != input.ID {
		return nil, errors.New("expense not found")
	}
	return data, nil
}

// DeleteExpense is the resolver for the deleteExpense field.
func (r *mutationResolver) DeleteExpense(ctx context.Context, input model.DeleteExpense) (*model.Expense, error) {
	expense := dbHelpers.DeleteExpense(input.ID)
	data := &model.Expense{
		ID:      expense.ID,
		OwnerID: expense.OwnerID,
		Name:    expense.Name,
		Spent:   expense.Spent,
	}
	if data.ID != input.ID {
		return nil, errors.New("expense not found")
	}
	return data, nil
}

// Expenses is the resolver for the expenses field.
func (r *queryResolver) Expenses(ctx context.Context) ([]*model.Expense, error) {
	var expenses []*model.Expense
	data := dbHelpers.GetAllExpenses()
	for _, r := range data {
		expenses = append(expenses, &model.Expense{
			ID:      r.ID,
			OwnerID: r.OwnerID,
			Name:    r.Name,
			Spent:   r.Spent,
//			DateCreated:    r.DateCreated,
		})
	}
	return expenses, nil
}

// Expense is the resolver for the expense field.
func (r *queryResolver) Expense(ctx context.Context, id string) (*model.Expense, error) {
	data := dbHelpers.GetExpenseById(id)
	expense := &model.Expense{
		ID:      data.ID,
		OwnerID: data.OwnerID,
		Name:    data.Name,
		Spent:   data.Spent,
		Date:    data.Date,
	}
	if expense.ID != id {
		return nil, errors.New("expense not found")
	}
	return expense, nil
}

// ExpensesHigherThan is the resolver for the expensesHigherThan field.
func (r *queryResolver) ExpensesHigherThan(ctx context.Context, spent int, ownerID string) ([]*model.Expense, error) {
	var expenses []*model.Expense
	data := dbHelpers.ExpensesHigherThan(spent, ownerID)
	for _, r := range data {
		expenses = append(expenses, &model.Expense{
			ID:      r.ID,
			OwnerID: r.OwnerID,
			Name:    r.Name,
			Spent:   r.Spent,
			Date:    r.Date,
		})
	}
	if len(expenses) <= 0 {
		return nil, errors.New("expenses not found")
	}
	return expenses, nil
}

// ExpensesLowerThan is the resolver for the expensesLowerThan field.
func (r *queryResolver) ExpensesLowerThan(ctx context.Context, spent int, ownerID string) ([]*model.Expense, error) {
	var expenses []*model.Expense
	data := dbHelpers.ExpensesLowerThan(spent, ownerID)
	for _, r := range data {
		expenses = append(expenses, &model.Expense{
			ID:      r.ID,
			OwnerID: r.OwnerID,
			Name:    r.Name,
			Spent:   r.Spent,
			Date:    r.Date,
		})
	}
	if len(expenses) <= 0 {
		return nil, errors.New("expenses not found")
	}
	return expenses, nil
}

// MostExpensiveExpense is the resolver for the mostExpensiveExpense field.
func (r *queryResolver) MostExpensiveExpense(ctx context.Context, ownerID string) (*model.Expense, error) {
	data := dbHelpers.MostExpensiveExpense(ownerID)
	expense := &model.Expense{
		ID:      data.ID,
		OwnerID: data.OwnerID,
		Name:    data.Name,
		Spent:   data.Spent,
		Date:    data.Date,
	}
	if expense.ID == "" {
		return nil, errors.New("There are no expenses")
	}
	return expense, nil
}

// LeastExpensiveExpense is the resolver for the leastExpensiveExpense field.
func (r *queryResolver) LeastExpensiveExpense(ctx context.Context, ownerID string) (*model.Expense, error) {
	data := dbHelpers.LeastExpensiveExpense(ownerID)
	expense := &model.Expense{
		ID:      data.ID,
		OwnerID: data.OwnerID,
		Name:    data.Name,
		Spent:   data.Spent,
		Date:    data.Date,
	}
	if expense.ID == "" {
		return nil, errors.New("There are no expenses")
	}
	return expense, nil
}

// ExpensesFromOwner is the resolver for the expensesFromOwner field.
func (r *queryResolver) ExpensesFromOwner(ctx context.Context, id string) ([]*model.Expense, error) {
	data := dbHelpers.GetExpensesByOwnerId(id)
	var expenses []*model.Expense
	for _, r := range data {
		if r.ID == "" {
			return nil, errors.New("There are no expenses")
		}
		expenses = append(expenses, &model.Expense{
			ID:      r.ID,
			OwnerID: r.OwnerID,
			Name:    r.Name,
			Spent:   r.Spent,
			Date:    r.Date,
		})
	}
	return expenses, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) MostExpensive(ctx context.Context, ownerID int) (*model.Expense, error) {
	panic(fmt.Errorf("not implemented: MostExpensive - mostExpensive"))
}
func (r *queryResolver) LeastExpensive(ctx context.Context, ownerID int) (*model.Expense, error) {
	panic(fmt.Errorf("not implemented: LeastExpensive - leastExpensive"))
}
func (r *queryResolver) ExpenseHigherThan(ctx context.Context, spent int, ownerID int) ([]*model.Expense, error) {
	panic(fmt.Errorf("not implemented: ExpenseHigherThan - expenseHigherThan"))
}
func (r *queryResolver) ExpenseLowerThan(ctx context.Context, spent int, ownerID int) ([]*model.Expense, error) {
	panic(fmt.Errorf("not implemented: ExpenseLowerThan - expenseLowerThan"))
}
func (r *queryResolver) LastExpense(ctx context.Context, ownerID string) (*model.Expense, error) {
	panic(fmt.Errorf("not implemented: LastExpense - lastExpense"))
}
func (r *queryResolver) ExpenseFromOwner(ctx context.Context, id string) (*model.Expense, error) {
	panic(fmt.Errorf("not implemented: ExpenseFromOwner - expenseFromOwner"))
}
