version: 'latest'

services:
  userDatabase:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${name}
      POSTGRES_URL: ${user}
    volumes:
        - expensedata:/var/lib/postgresql/data
    ports:
      - "${port}:5432"
volumes:
  expensedata:
