version: 'latest'

services:
  expensesDatabase:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: YfWLumYuoQfCwZFLyJz8Hc27DxNfsWVfz
      POSTGRES_DB: pennyearned
    volumes:
        - expensedata:/var/lib/postgresql/data
    ports:
      - "54320:5432"
volumes:
  expensedata:

