// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Expense struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
	Name    string `json:"name"`
	Spent   int    `json:"spent"`
}

type NewExpense struct {
	OwnerID string `json:"owner_id"`
	Name    string `json:"name"`
	Spent   int    `json:"spent"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
