// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteExpense struct {
	ID string `json:"id"`
}

type Expense struct {
	ID          string `json:"id"`
	OwnerID     string `json:"owner_id"`
	Name        string `json:"name"`
	Spent       int    `json:"spent"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
}

type NewExpense struct {
	OwnerID string `json:"owner_id"`
	Name    string `json:"name"`
	Spent   int    `json:"spent"`
}

type NewUser struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UpdateExpenseInput struct {
	OwnerID *string `json:"owner_id"`
	ID      string  `json:"id"`
	Name    *string `json:"name"`
	Spent   *int    `json:"spent"`
}

type UpdateUser struct {
	Name     *string `json:"name"`
	Username *string `json:"username"`
	Password string  `json:"password"`
	NewPass  *string `json:"newPass"`
	Email    string  `json:"email"`
	NewEmail *string `json:"newEmail"`
}

type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
}
